### ISSUE TITLE
[feat] Retool Fixes & Projects Awaiting Approval Page

### ISSUE THREAD

**Issue by itsliterallymonique** [calblueprint/ace-ny#92]
This week, you will be fixing the retool and adding the Projects Awaiting Approval Page:
1. Fixing the retool
       a. Right now, if we want to go to an individual project we have to click on the tab on the top. However, we don’t want this. You need to 1) hide this tab, 2) make it so that when I click on a project, it will redirect me to the individual project page, and 3) add a back button that when pressed, will send the user back to the “All Projects” Table
2. Make the Projects Awaiting Approval Page (as a new tab / view):
       a. We want to add a table that holds all projects where approved == FALSE in the database.
       b. For each row, we want to have a checkbox to approve and when the user clicks the checkbox, approved == TRUE.
       c. A button to “mass approve” all projects in the table.

**Comment by ethan-tam33** [comment]
<img width="1074" alt="Screenshot 2024-12-02 at 3 08 54 AM" src="https://github.com/user-attachments/assets/bbd0fdea-fe0f-43a4-a8df-ed212fbcd916">
<img width="1132" alt="Screenshot 2024-12-02 at 3 09 06 AM" src="https://github.com/user-attachments/assets/440d8417-fd9f-4348-9f2a-982bb6378293">

Retool link is [here](https://moniquemc1.retool.com/apps/2ced83ee-8467-11ef-9dc5-e7b7a96cb8be/ACE%20NY%20admin%20dashboard/allProjects). The "Projects Waiting Approval" page is empty since all the projects have approval.

**Comment by itsliterallymonique** [comment]
@ethan-tam33 can you add these parts to the projects awaiting approval page:
1. For each row, we want to have a checkbox to approve and when the user clicks the checkbox, approved == TRUE.
2. A button to “mass approve” all projects in the table.

I can't see it on the retool

**Comment by itsliterallymonique** [comment]
@ethan-tam33 you still need to add the "approve all" button that will automatically approve all entries in the table. Please finish it by tonight. This sprint was due Yesterday.

**Comment by ethan-tam33** [comment]
<img width="1337" alt="Screenshot 2024-12-04 at 10 51 51 PM" src="https://github.com/user-attachments/assets/5ac0794f-09ba-4ea5-940a-40712b8c4305">
